const Cities  =
[
  {label:'Adolfo',value:'Adolfo'},
  {label:'Aguaí  ',value:'Aguaí  '},
  {label:'Águas da Prata',value:'Águas da Prata'},
  {label:'Águas de Lindóia',value:'Águas de Lindóia'},
  {label:'Águas de Santa Bárbara',value:'Águas de Santa Bárbara'},
  {label:'Águas de São Pedro',value:'Águas de São Pedro'},
  {label:'Agudos',value:'Agudos'},
  {label:'Adolfo',value:'Adolfo'},
  {label:'Alambari',value:'Alambari'},
  {label:'Alfredo Marcondes',value:'Alfredo Marcondes'},
  {label:'Altair',value:'Altair'},
  {label:'Altinópolis',value:'Altinópolis'},
  {label:'Alto Alegre',value:'Alto Alegre'},
  {label:'Alumínio',value:'Alumínio'},
  {label:'Álvares Florence',value:'Álvares Florence'},
  {label:'Álvares Machado',value:'Álvares Machado'},
  {label:'Álvaro de Carvalho',value:'Álvaro de Carvalho'},
  {label:'Alvinlândia',value:'Alvinlândia'},
  {label:'Americana',value:'Americana'},
  {label:'Américo Brasiliense',value:'Américo Brasiliense'},
  {label:'Américo de Campos',value:'Américo de Campos'},
  {label:'Amparo',value:'Amparo'},
  {label:'Analândia',value:'Analândia'},
  {label:'Andradina',value:'Andradina'},
  {label:'Angatuba',value:'Angatuba'},
  {label:'Anhembi',value:'Anhembi'},
  {label:'Anhumas',value:'Anhumas'},
  {label:'Aparecida',value:'Aparecida'},
  {label:'Aparecida d Oeste',value:'Aparecida d Oeste'},
  {label:'Apiaí',value:'Apiaí'},
  {label:'Araçariguama',value:'Araçariguama'},
  {label:'Araçatuba',value:'Araçatuba'},
  {label:'Araçoiaba da Serra',value:'Araçoiaba da Serra'},
  {label:'Aramina',value:'Aramina'},
  {label:'Arandu',value:'Arandu'},
  {label:'Arapeí',value:'Arapeí'},
  {label:'Araraquara',value:'Araraquara'},
  {label:'Araras',value:'Araras'},
  {label:'Arco-Íris',value:'Arco-Íris'},
  {label:'Arealva',value:'Arealva'},
  {label:'Areias',value:'Areias'},
  {label:'Areiópolis',value:'Areiópolis'},
  {label:'Ariranha',value:'Ariranha'},
  {label:'Artur Nogueira',value:'Artur Nogueira'},
  {label:'Arujá',value:'Arujá'},
  {label:'Aspásia',value:'Aspásia'},
  {label:'Assis',value:'Assis'},
  {label:'Atibaia',value:'Atibaia'},
  {label:'Auriflama',value:'Auriflama'},
  {label:'Avaí',value:'Avaí'},
  {label:'Avanhandava',value:'Avanhandava'},
  {label:'Avaré',value:'Avaré'},
  {label:'Bady Bassitt',value:'Bady Bassitt'},
  {label:'Balbinos',value:'Balbinos'},
  {label:'Bálsamo',value:'Bálsamo'},
  {label:'Bananal',value:'Bananal'},
  {label:'Barão de Antonina',value:'Barão de Antonina'},
  {label:'Barbosa',value:'Barbosa'},
  {label:'Bariri',value:'Bariri'},
  {label:'Barra Bonita',value:'Barra Bonita'},
  {label:'Barra do Chapéu',value:'Barra do Chapéu'},
  {label:'Barra do Turvo',value:'Barra do Turvo'},
  {label:'Barretos',value:'Barretos'},
  {label:'Barrinha',value:'Barrinha'},
  {label:'Barueri',value:'Barueri'},
  {label:'Bastos',value:'Bastos'},
  {label:'Batatais',value:'Batatais'},
  {label:'Bauru',value:'Bauru'},
  {label:'Bebedouro',value:'Bebedouro'},
  {label:'Bento de Abreu',value:'Bento de Abreu'},
  {label:'Bernardino de Campos',value:'Bernardino de Campos'},
  {label:'Bertioga',value:'Bertioga'},
  {label:'Bilac',value:'Bilac'},
  {label:'Birigui',value:'Birigui'},
  {label:'Biritiba-Mirim',value:'Biritiba-Mirim'},
  {label:'Boa Esperança do Sul',value:'Boa Esperança do Sul'},
  {label:'Bocaina',value:'Bocaina'},
  {label:'Bofete',value:'Bofete'},
  {label:'Boituva',value:'Boituva'},
  {label:'Bom Jesus dos Perdões',value:'Bom Jesus dos Perdões'},
  {label:'Bom Sucesso de Itararé',value:'Bom Sucesso de Itararé'},
  {label:'Borá',value:'Borá'},
  {label:'Boracéia',value:'Boracéia'},
  {label:'Borborema',value:'Borborema'},
  {label:'Borebi',value:'Borebi'},
  {label:'Botucatu',value:'Botucatu'},
  {label:'Bragança Paulista',value:'Bragança Paulista'},
  {label:'Braúna',value:'Braúna'},
  {label:'Brejo Alegre',value:'Brejo Alegre'},
  {label:'Brodowski',value:'Brodowski'},
  {label:'Brotas',value:'Brotas'},
  {label:'Buri',value:'Buri'},
  {label:'Buritama',value:'Buritama'},
  {label:'Buritizal',value:'Buritizal'},
  {label:'Cabrália Paulista',value:'Cabrália Paulista'},
  {label:'Cabreúva',value:'Cabreúva'},
  {label:'Caçapava',value:'Caçapava'},
  {label:'Cachoeira Paulista',value:'Cachoeira Paulista'},
  {label:'Caconde',value:'Caconde'},
  {label:'Cafelândia',value:'Cafelândia'},
  {label:'Caiabu',value:'Caiabu'},
  {label:'Caieiras',value:'Caieiras'},
  {label:'Caiuá',value:'Caiuá'},
  {label:'Cajamar',value:'Cajamar'},
  {label:'Cajati',value:'Cajati'},
  {label:'Cajobi',value:'Cajobi'},
  {label:'Cajuru',value:'Cajuru'},
  {label:'Campina do Monte Alegre',value:'Campina do Monte Alegre'},
  {label:'Campinas',value:'Campinas'},
  {label:'Campo Limpo Paulista',value:'Campo Limpo Paulista'},
  {label:'Campos do Jordão',value:'Campos do Jordão'},
  {label:'Campos Novos Paulista',value:'Campos Novos Paulista'},
  {label:'Cananéia',value:'Cananéia'},
  {label:'Canas',value:'Canas'},
  {label:'Cândido Mota',value:'Cândido Mota'},
  {label:'Cândido Rodrigues',value:'Cândido Rodrigues'},
  {label:'Canitar',value:'Canitar'},
  {label:'Capão Bonito',value:'Capão Bonito'},
  {label:'Capela do Alto',value:'Capela do Alto'},
  {label:'Capivari',value:'Capivari'},
  {label:'Caraguatatuba',value:'Caraguatatuba'},
  {label:'Carapicuíba',value:'Carapicuíba'},
  {label:'Cardoso',value:'Cardoso'},
  {label:'Casa Branca',value:'Casa Branca'},
  {label:'Cássia dos Coqueiros',value:'Cássia dos Coqueiros'},
  {label:'Castilho',value:'Castilho'},
  {label:'Catanduva',value:'Catanduva'},
  {label:'Catiguá',value:'Catiguá'},
  {label:'Cedral',value:'Cedral'},
  {label:'Cerqueira César',value:'Cerqueira César'},
  {label:'Cerquilho',value:'Cerquilho'},
  {label:'Cesário Lange',value:'Cesário Lange'},
  {label:'Charqueada',value:'Charqueada'},
  {label:'Chavantes',value:'Chavantes'},
  {label:'Clementina',value:'Clementina'},
  {label:'Colina',value:'Colina'},
  {label:'Colômbia',value:'Colômbia'},
  {label:'Conchal',value:'Conchal'},
  {label:'Conchas',value:'Conchas'},
  {label:'Cordeirópolis',value:'Cordeirópolis'},
  {label:'Coroados',value:'Coroados'},
  {label:'Coronel Macedo',value:'Coronel Macedo'},
  {label:'Corumbataí',value:'Corumbataí'},
  {label:'Cosmópolis',value:'Cosmópolis'},
  {label:'Cosmorama',value:'Cosmorama'},
  {label:'Cotia',value:'Cotia'},
  {label:'Cravinhos',value:'Cravinhos'},
  {label:'Cristais Paulista',value:'Cristais Paulista'},
  {label:'Cruzália',value:'Cruzália'},
  {label:'Cruzeiro',value:'Cruzeiro'},
  {label:'Cubatão',value:'Cubatão'},
  {label:'Cunha',value:'Cunha'},
  {label:'Descalvado',value:'Descalvado'},
  {label:'Diadema',value:'Diadema'},
  {label:'Dirce Reis',value:'Dirce Reis'},
  {label:'Divinolândia',value:'Divinolândia'},
  {label:'Dobrada',value:'Dobrada'},
  {label:'Dois Córregos',value:'Dois Córregos'},
  {label:'Dolcinópolis',value:'Dolcinópolis'},
  {label:'Dourado',value:'Dourado'},
  {label:'Dracena',value:'Dracena'},
  {label:'Duartina',value:'Duartina'},
  {label:'Dumont',value:'Dumont'},
  {label:'Echaporã',value:'Echaporã'},
  {label:'Eldorado',value:'Eldorado'},
  {label:'Elias Fausto',value:'Elias Fausto'},
  {label:'Elisiário',value:'Elisiário'},
  {label:'Embaúba',value:'Embaúba'},
  {label:'Embu',value:'Embu'},
  {label:'Embu-Guaçu',value:'Embu-Guaçu'},
  {label:'Emilianópolis',value:'Emilianópolis'},
  {label:'Engenheiro Coelho',value:'Engenheiro Coelho'},
  {label:'Espírito Santo do Pinhal',value:'Espírito Santo do Pinhal'},
  {label:'Espírito Santo do Turvo',value:'Espírito Santo do Turvo'},
  {label:'Estiva Gerbi',value:'Estiva Gerbi'},
  {label:'Estrela do Norte',value:'Estrela do Norte'},
  {label:'Estrela d Oeste',value:'Estrela d Oeste'},
  {label:'Euclides da Cunha Paulista',value:'Euclides da Cunha Paulista'},
  {label:'Fartura',value:'Fartura'},
  {label:'Fernando Prestes',value:'Fernando Prestes'},
  {label:'Fernandópolis',value:'Fernandópolis'},
  {label:'Fernão',value:'Fernão'},
  {label:'Ferraz de Vasconcelos',value:'Ferraz de Vasconcelos'},
  {label:'Flora Rica',value:'Flora Rica'},
  {label:'Floreal',value:'Floreal'},
  {label:'Flórida Paulista',value:'Flórida Paulista'},
  {label:'Florínia',value:'Florínia'},
  {label:'Franca',value:'Franca'},
  {label:'Francisco Morato',value:'Francisco Morato'},
  {label:'Franco da Rocha',value:'Franco da Rocha'},
  {label:'Gabriel Monteiro',value:'Gabriel Monteiro'},
  {label:'Gália',value:'Gália'},
  {label:'Garça',value:'Garça'},
  {label:'Gastão Vidigal',value:'Gastão Vidigal'},
  {label:'Gavião Peixoto',value:'Gavião Peixoto'},
  {label:'General Salgado',value:'General Salgado'},
  {label:'Getulina',value:'Getulina'},
  {label:'Glicério',value:'Glicério'},
  {label:'Guaiçara',value:'Guaiçara'},
  {label:'Guaimbê',value:'Guaimbê'},
  {label:'Guaíra',value:'Guaíra'},
  {label:'Guapiaçu',value:'Guapiaçu'},
  {label:'Guapiara',value:'Guapiara'},
  {label:'Guará',value:'Guará'},
  {label:'Guaraçaí',value:'Guaraçaí'},
  {label:'Guaraci',value:'Guaraci'},
  {label:'Guarani d Oeste',value:'Guarani d Oeste'},
  {label:'Guarantã',value:'Guarantã'},
  {label:'Guararapes',value:'Guararapes'},
  {label:'Guararema',value:'Guararema'},
  {label:'Guaratinguetá',value:'Guaratinguetá'},
  {label:'Guareí',value:'Guareí'},
  {label:'Guariba',value:'Guariba'},
  {label:'Guarujá',value:'Guarujá'},
  {label:'Guarulhos',value:'Guarulhos'},
  {label:'Guatapará',value:'Guatapará'},
  {label:'Guzolândia',value:'Guzolândia'},
  {label:'Herculândia',value:'Herculândia'},
  {label:'Holambra',value:'Holambra'},
  {label:'Hortolândia',value:'Hortolândia'},
  {label:'Iacanga',value:'Iacanga'},
  {label:'Iacri',value:'Iacri'},
  {label:'Iaras',value:'Iaras'},
  {label:'Ibaté',value:'Ibaté'},
  {label:'Ibirá',value:'Ibirá'},
  {label:'Ibirarema',value:'Ibirarema'},
  {label:'Ibitinga',value:'Ibitinga'},
  {label:'Ibiúna',value:'Ibiúna'},
  {label:'Icém',value:'Icém'},
  {label:'Iepê',value:'Iepê'},
  {label:'Igaraçu do Tietê',value:'Igaraçu do Tietê'},
  {label:'Igarapava',value:'Igarapava'},
  {label:'Igaratá',value:'Igaratá'},
  {label:'Iguape',value:'Iguape'},
  {label:'Ilha Comprida',value:'Ilha Comprida'},
  {label:'Ilha Solteira',value:'Ilha Solteira'},
  {label:'Ilhabela',value:'Ilhabela'},
  {label:'Indaiatuba',value:'Indaiatuba'},
  {label:'Indiana',value:'Indiana'},
  {label:'Indiaporã',value:'Indiaporã'},
  {label:'Inúbia Paulista',value:'Inúbia Paulista'},
  {label:'Ipaussu',value:'Ipaussu'},
  {label:'Iperó',value:'Iperó'},
  {label:'Ipeúna',value:'Ipeúna'},
  {label:'Ipiguá',value:'Ipiguá'},
  {label:'Iporanga',value:'Iporanga'},
  {label:'Ipuã',value:'Ipuã'},
  {label:'Iracemápolis',value:'Iracemápolis'},
  {label:'Irapuã',value:'Irapuã'},
  {label:'Irapuru',value:'Irapuru'},
  {label:'Itaberá',value:'Itaberá'},
  {label:'Itaí',value:'Itaí'},
  {label:'Itajobi',value:'Itajobi'},
  {label:'Itaju',value:'Itaju'},
  {label:'Itanhaém',value:'Itanhaém'},
  {label:'Itaóca',value:'Itaóca'},
  {label:'Itapecerica da Serra',value:'Itapecerica da Serra'},
  {label:'Itapetininga',value:'Itapetininga'},
  {label:'Itapeva',value:'Itapeva'},
  {label:'Itapevi',value:'Itapevi'},
  {label:'Itapira',value:'Itapira'},
  {label:'Itapirapuã Paulista',value:'Itapirapuã Paulista'},
  {label:'Itápolis',value:'Itápolis'},
  {label:'Itaporanga',value:'Itaporanga'},
  {label:'Itapuí',value:'Itapuí'},
  {label:'Itapura',value:'Itapura'},
  {label:'Itaquaquecetuba',value:'Itaquaquecetuba'},
  {label:'Itararé',value:'Itararé'},
  {label:'Itariri',value:'Itariri'},
  {label:'Itatiba',value:'Itatiba'},
  {label:'Itatinga',value:'Itatinga'},
  {label:'Itirapina',value:'Itirapina'},
  {label:'Itirapuã',value:'Itirapuã'},
  {label:'Itobi',value:'Itobi'},
  {label:'Itu',value:'Itu'},
  {label:'Itupeva',value:'Itupeva'},
  {label:'Ituverava',value:'Ituverava'},
  {label:'Jaborandi',value:'Jaborandi'},
  {label:'Jaboticabal',value:'Jaboticabal'},
  {label:'Jacareí',value:'Jacareí'},
  {label:'Jaci',value:'Jaci'},
  {label:'Jacupiranga',value:'Jacupiranga'},
  {label:'Jaguariúna',value:'Jaguariúna'},
  {label:'Jales',value:'Jales'},
  {label:'Jambeiro',value:'Jambeiro'},
  {label:'Jandira',value:'Jandira'},
  {label:'Jardinópolis',value:'Jardinópolis'},
  {label:'Jarinu',value:'Jarinu'},
  {label:'Jaú',value:'Jaú'},
  {label:'Jeriquara',value:'Jeriquara'},
  {label:'Joanópolis',value:'Joanópolis'},
  {label:'João Ramalho',value:'João Ramalho'},
  {label:'José Bonifácio',value:'José Bonifácio'},
  {label:'Júlio Mesquita',value:'Júlio Mesquita'},
  {label:'Jumirim',value:'Jumirim'},
  {label:'Jundiaí',value:'Jundiaí'},
  {label:'Junqueirópolis',value:'Junqueirópolis'},
  {label:'Juquiá',value:'Juquiá'},
  {label:'Juquitiba',value:'Juquitiba'},
  {label:'Lagoinha',value:'Lagoinha'},
  {label:'Laranjal Paulista',value:'Laranjal Paulista'},
  {label:'Lavínia',value:'Lavínia'},
  {label:'Lavrinhas',value:'Lavrinhas'},
  {label:'Leme',value:'Leme'},
  {label:'Lençóis Paulista',value:'Lençóis Paulista'},
  {label:'Limeira',value:'Limeira'},
  {label:'Lindóia',value:'Lindóia'},
  {label:'Lins',value:'Lins'},
  {label:'Lorena',value:'Lorena'},
  {label:'Lourdes',value:'Lourdes'},
  {label:'Louveira',value:'Louveira'},
  {label:'Lucélia',value:'Lucélia'},
  {label:'Lucianópolis',value:'Lucianópolis'},
  {label:'Luís Antônio',value:'Luís Antônio'},
  {label:'Luiziânia',value:'Luiziânia'},
  {label:'Lupércio',value:'Lupércio'},
  {label:'Lutécia',value:'Lutécia'},
  {label:'Macatuba',value:'Macatuba'},
  {label:'Macaubal',value:'Macaubal'},
  {label:'Macedônia',value:'Macedônia'},
  {label:'Magda',value:'Magda'},
  {label:'Mairinque',value:'Mairinque'},
  {label:'Mairiporã',value:'Mairiporã'},
  {label:'Manduri',value:'Manduri'},
  {label:'Marabá Paulista',value:'Marabá Paulista'},
  {label:'Maracaí',value:'Maracaí'},
  {label:'Marapoama',value:'Marapoama'},
  {label:'Mariápolis',value:'Mariápolis'},
  {label:'Marília',value:'Marília'},
  {label:'Marinópolis',value:'Marinópolis'},
  {label:'Martinópolis',value:'Martinópolis'},
  {label:'Matão',value:'Matão'},
  {label:'Mauá',value:'Mauá'},
  {label:'Mendonça',value:'Mendonça'},
  {label:'Meridiano',value:'Meridiano'},
  {label:'Mesópolis',value:'Mesópolis'},
  {label:'Miguelópolis',value:'Miguelópolis'},
  {label:'Mineiros do Tietê',value:'Mineiros do Tietê'},
  {label:'Mira Estrela',value:'Mira Estrela'},
  {label:'Miracatu',value:'Miracatu'},
  {label:'Mirandópolis',value:'Mirandópolis'},
  {label:'Mirante do Paranapanema',value:'Mirante do Paranapanema'},
  {label:'Mirassol',value:'Mirassol'},
  {label:'Mirassolândia',value:'Mirassolândia'},
  {label:'Mococa',value:'Mococa'},
  {label:'Mogi das Cruzes',value:'Mogi das Cruzes'},
  {label:'Mogi Guaçu',value:'Mogi Guaçu'},
  {label:'Moji Mirim',value:'Moji Mirim'},
  {label:'Mombuca',value:'Mombuca'},
  {label:'Monções',value:'Monções'},
  {label:'Mongaguá',value:'Mongaguá'},
  {label:'Monte Alegre do Sul',value:'Monte Alegre do Sul'},
  {label:'Monte Alto',value:'Monte Alto'},
  {label:'Monte Aprazível',value:'Monte Aprazível'},
  {label:'Monte Azul Paulista',value:'Monte Azul Paulista'},
  {label:'Monte Castelo',value:'Monte Castelo'},
  {label:'Monte Mor',value:'Monte Mor'},
  {label:'Monteiro Lobato',value:'Monteiro Lobato'},
  {label:'Morro Agudo',value:'Morro Agudo'},
  {label:'Morungaba',value:'Morungaba'},
  {label:'Motuca',value:'Motuca'},
  {label:'Murutinga do Sul',value:'Murutinga do Sul'},
  {label:'Nantes',value:'Nantes'},
  {label:'Narandiba',value:'Narandiba'},
  {label:'Natividade da Serra',value:'Natividade da Serra'},
  {label:'Nazaré Paulista',value:'Nazaré Paulista'},
  {label:'Neves Paulista',value:'Neves Paulista'},
  {label:'Nhandeara',value:'Nhandeara'},
  {label:'Nipoã',value:'Nipoã'},
  {label:'Nova Aliança',value:'Nova Aliança'},
  {label:'Nova Campina',value:'Nova Campina'},
  {label:'Nova Canaã Paulista',value:'Nova Canaã Paulista'},
  {label:'Nova Castilho',value:'Nova Castilho'},
  {label:'Nova Europa',value:'Nova Europa'},
  {label:'Nova Granada',value:'Nova Granada'},
  {label:'Nova Guataporanga',value:'Nova Guataporanga'},
  {label:'Nova Independência',value:'Nova Independência'},
  {label:'Nova Luzitânia',value:'Nova Luzitânia'},
  {label:'Nova Odessa',value:'Nova Odessa'},
  {label:'Novais',value:'Novais'},
  {label:'Novo Horizonte',value:'Novo Horizonte'},
  {label:'Nuporanga',value:'Nuporanga'},
  {label:'Ocauçu',value:'Ocauçu'},
  {label:'Óleo',value:'Óleo'},
  {label:'Olímpia',value:'Olímpia'},
  {label:'Onda Verde',value:'Onda Verde'},
  {label:'Oriente',value:'Oriente'},
  {label:'Orindiúva',value:'Orindiúva'},
  {label:'Orlândia',value:'Orlândia'},
  {label:'Osasco',value:'Osasco'},
  {label:'Oscar Bressane',value:'Oscar Bressane'},
  {label:'Osvaldo Cruz',value:'Osvaldo Cruz'},
  {label:'Ourinhos',value:'Ourinhos'},
  {label:'Ouro Verde',value:'Ouro Verde'},
  {label:'Ouroeste',value:'Ouroeste'},
  {label:'Pacaembu',value:'Pacaembu'},
  {label:'Palestina',value:'Palestina'},
  {label:'Palmares Paulista',value:'Palmares Paulista'},
  {label:'Palmeira d Oeste',value:'Palmeira d Oeste'},
  {label:'Palmital',value:'Palmital'},
  {label:'Panorama',value:'Panorama'},
  {label:'Paraguaçu Paulista',value:'Paraguaçu Paulista'},
  {label:'Paraibuna',value:'Paraibuna'},
  {label:'Paraíso',value:'Paraíso'},
  {label:'Paranapanema',value:'Paranapanema'},
  {label:'Paranapuã',value:'Paranapuã'},
  {label:'Parapuã',value:'Parapuã'},
  {label:'Pardinho',value:'Pardinho'},
  {label:'Pariquera-Açu',value:'Pariquera-Açu'},
  {label:'Parisi',value:'Parisi'},
  {label:'Patrocínio Paulista',value:'Patrocínio Paulista'},
  {label:'Paulicéia',value:'Paulicéia'},
  {label:'Paulínia',value:'Paulínia'},
  {label:'Paulistânia',value:'Paulistânia'},
  {label:'Paulo de Faria',value:'Paulo de Faria'},
  {label:'Pederneiras',value:'Pederneiras'},
  {label:'Pedra Bela',value:'Pedra Bela'},
  {label:'Pedranópolis',value:'Pedranópolis'},
  {label:'Pedregulho',value:'Pedregulho'},
  {label:'Pedreira',value:'Pedreira'},
  {label:'Pedrinhas Paulista',value:'Pedrinhas Paulista'},
  {label:'Pedro de Toledo',value:'Pedro de Toledo'},
  {label:'Penápolis',value:'Penápolis'},
  {label:'Pereira Barreto',value:'Pereira Barreto'},
  {label:'Pereiras',value:'Pereiras'},
  {label:'Peruíbe',value:'Peruíbe'},
  {label:'Piacatu',value:'Piacatu'},
  {label:'Piedade',value:'Piedade'},
  {label:'Pilar do Sul',value:'Pilar do Sul'},
  {label:'Pindamonhangaba',value:'Pindamonhangaba'},
  {label:'Pindorama',value:'Pindorama'},
  {label:'Pinhalzinho',value:'Pinhalzinho'},
  {label:'Piquerobi',value:'Piquerobi'},
  {label:'Piquete',value:'Piquete'},
  {label:'Piracaia',value:'Piracaia'},
  {label:'Piracicaba',value:'Piracicaba'},
  {label:'Piraju',value:'Piraju'},
  {label:'Pirajuí',value:'Pirajuí'},
  {label:'Pirangi',value:'Pirangi'},
  {label:'Pirapora do Bom Jesus',value:'Pirapora do Bom Jesus'},
  {label:'Pirapozinho',value:'Pirapozinho'},
  {label:'Pirassununga',value:'Pirassununga'},
  {label:'Piratininga',value:'Piratininga'},
  {label:'Pitangueiras',value:'Pitangueiras'},
  {label:'Planalto',value:'Planalto'},
  {label:'Platina',value:'Platina'},
  {label:'Poá',value:'Poá'},
  {label:'Poloni',value:'Poloni'},
  {label:'Pompéia',value:'Pompéia'},
  {label:'Pongaí',value:'Pongaí'},
  {label:'Pontal',value:'Pontal'},
  {label:'Pontalinda',value:'Pontalinda'},
  {label:'Pontes Gestal',value:'Pontes Gestal'},
  {label:'Populina',value:'Populina'},
  {label:'Porangaba',value:'Porangaba'},
  {label:'Porto Feliz',value:'Porto Feliz'},
  {label:'Porto Ferreira',value:'Porto Ferreira'},
  {label:'Potim',value:'Potim'},
  {label:'Potirendaba',value:'Potirendaba'},
  {label:'Pracinha',value:'Pracinha'},
  {label:'Pradópolis',value:'Pradópolis'},
  {label:'Praia Grande',value:'Praia Grande'},
  {label:'Pratânia',value:'Pratânia'},
  {label:'Presidente Alves',value:'Presidente Alves'},
  {label:'Presidente Bernardes',value:'Presidente Bernardes'},
  {label:'Presidente Epitácio',value:'Presidente Epitácio'},
  {label:'Presidente Prudente',value:'Presidente Prudente'},
  {label:'Presidente Venceslau',value:'Presidente Venceslau'},
  {label:'Promissão',value:'Promissão'},
  {label:'Quadra',value:'Quadra'},
  {label:'Quatá',value:'Quatá'},
  {label:'Queiroz',value:'Queiroz'},
  {label:'Queluz',value:'Queluz'},
  {label:'Quintana',value:'Quintana'},
  {label:'Rafard',value:'Rafard'},
  {label:'Rancharia',value:'Rancharia'},
  {label:'Redenção da Serra',value:'Redenção da Serra'},
  {label:'Regente Feijó',value:'Regente Feijó'},
  {label:'Reginópolis',value:'Reginópolis'},
  {label:'Registro',value:'Registro'},
  {label:'Restinga',value:'Restinga'},
  {label:'Ribeira',value:'Ribeira'},
  {label:'Ribeirão Bonito',value:'Ribeirão Bonito'},
  {label:'Ribeirão Branco',value:'Ribeirão Branco'},
  {label:'Ribeirão Corrente',value:'Ribeirão Corrente'},
  {label:'Ribeirão do Sul',value:'Ribeirão do Sul'},
  {label:'Ribeirão dos Índios',value:'Ribeirão dos Índios'},
  {label:'Ribeirão Grande',value:'Ribeirão Grande'},
  {label:'Ribeirão Pires',value:'Ribeirão Pires'},
  {label:'Ribeirão Preto',value:'Ribeirão Preto'},
  {label:'Rifaina',value:'Rifaina'},
  {label:'Rincão',value:'Rincão'},
  {label:'Rinópolis',value:'Rinópolis'},
  {label:'Rio Claro',value:'Rio Claro'},
  {label:'Rio das Pedras',value:'Rio das Pedras'},
  {label:'Rio Grande da Serra',value:'Rio Grande da Serra'},
  {label:'Riolândia',value:'Riolândia'},
  {label:'Riversul',value:'Riversul'},
  {label:'Rosana',value:'Rosana'},
  {label:'Roseira',value:'Roseira'},
  {label:'Rubiácea',value:'Rubiácea'},
  {label:'Rubinéia',value:'Rubinéia'},
  {label:'Sabino',value:'Sabino'},
  {label:'Sagres',value:'Sagres'},
  {label:'Sales',value:'Sales'},
  {label:'Sales Oliveira',value:'Sales Oliveira'},
  {label:'Salesópolis',value:'Salesópolis'},
  {label:'Salmourão',value:'Salmourão'},
  {label:'Saltinho',value:'Saltinho'},
  {label:'Salto',value:'Salto'},
  {label:'Salto de Pirapora',value:'Salto de Pirapora'},
  {label:'Salto Grande',value:'Salto Grande'},
  {label:'Sandovalina',value:'Sandovalina'},
  {label:'Santa Adélia',value:'Santa Adélia'},
  {label:'Santa Albertina',value:'Santa Albertina'},
  {label:'Santa Bárbara d Oeste',value:'Santa Bárbara d Oeste'},
  {label:'Santa Branca',value:'Santa Branca'},
  {label:'Santa Clara d Oeste',value:'Santa Clara d Oeste'},
  {label:'Santa Cruz da Conceição',value:'Santa Cruz da Conceição'},
  {label:'Santa Cruz da Esperança',value:'Santa Cruz da Esperança'},
  {label:'Santa Cruz das Palmeiras',value:'Santa Cruz das Palmeiras'},
  {label:'Santa Cruz do Rio Pardo',value:'Santa Cruz do Rio Pardo'},
  {label:'Santa Ernestina',value:'Santa Ernestina'},
  {label:'Santa Fé do Sul',value:'Santa Fé do Sul'},
  {label:'Santa Gertrudes',value:'Santa Gertrudes'},
  {label:'Santa Isabel',value:'Santa Isabel'},
  {label:'Santa Lúcia',value:'Santa Lúcia'},
  {label:'Santa Maria da Serra',value:'Santa Maria da Serra'},
  {label:'Santa Mercedes',value:'Santa Mercedes'},
  {label:'Santa Rita do Passa Quatro',value:'Santa Rita do Passa Quatro'},
  {label:'Santa Rita d Oeste',value:'Santa Rita d Oeste'},
  {label:'Santa Rosa de Viterbo',value:'Santa Rosa de Viterbo'},
  {label:'Santa Salete',value:'Santa Salete'},
  {label:'Santana da Ponte Pensa',value:'Santana da Ponte Pensa'},
  {label:'Santana de Parnaíba',value:'Santana de Parnaíba'},
  {label:'Santo Anastácio',value:'Santo Anastácio'},
  {label:'Santo André',value:'Santo André'},
  {label:'Santo Antônio da Alegria',value:'Santo Antônio da Alegria'},
  {label:'Santo Antônio de Posse',value:'Santo Antônio de Posse'},
  {label:'Santo Antônio do Aracanguá',value:'Santo Antônio do Aracanguá'},
  {label:'Santo Antônio do Jardim',value:'Santo Antônio do Jardim'},
  {label:'Santo Antônio do Pinhal',value:'Santo Antônio do Pinhal'},
  {label:'Santo Expedito',value:'Santo Expedito'},
  {label:'Santópolis do Aguapeí',value:'Santópolis do Aguapeí'},
  {label:'Santos',value:'Santos'},
  {label:'São Bento do Sapucaí',value:'São Bento do Sapucaí'},
  {label:'São Bernardo do Campo',value:'São Bernardo do Campo'},
  {label:'São Caetano do Sul',value:'São Caetano do Sul'},
  {label:'São Carlos',value:'São Carlos'},
  {label:'São Francisco',value:'São Francisco'},
  {label:'São João da Boa Vista',value:'São João da Boa Vista'},
  {label:'São João das Duas Pontes',value:'São João das Duas Pontes'},
  {label:'São João de Iracema',value:'São João de Iracema'},
  {label:'São João do Pau d Alho',value:'São João do Pau d Alho'},
  {label:'São Joaquim da Barra',value:'São Joaquim da Barra'},
  {label:'São José da Bela Vista',value:'São José da Bela Vista'},
  {label:'São José do Barreiro',value:'São José do Barreiro'},
  {label:'São José do Rio Pardo',value:'São José do Rio Pardo'},
  {label:'São José do Rio Preto',value:'São José do Rio Preto'},
  {label:'São José dos Campos',value:'São José dos Campos'},
  {label:'São Lourenço da Serra',value:'São Lourenço da Serra'},
  {label:'São Luís do Paraitinga',value:'São Luís do Paraitinga'},
  {label:'São Manuel',value:'São Manuel'},
  {label:'São Miguel Arcanjo',value:'São Miguel Arcanjo'},
  {label:'São Paulo',value:'São Paulo'},
  {label:'São Pedro',value:'São Pedro'},
  {label:'São Pedro do Turvo',value:'São Pedro do Turvo'},
  {label:'São Roque',value:'São Roque'},
  {label:'São Sebastião',value:'São Sebastião'},
  {label:'São Sebastião da Grama',value:'São Sebastião da Grama'},
  {label:'São Simão',value:'São Simão'},
  {label:'São Vicente',value:'São Vicente'},
  {label:'Sarapuí',value:'Sarapuí'},
  {label:'Sarutaiá',value:'Sarutaiá'},
  {label:'Sebastianópolis do Sul',value:'Sebastianópolis do Sul'},
  {label:'Serra Azul',value:'Serra Azul'},
  {label:'Serra Negra',value:'Serra Negra'},
  {label:'Serrana',value:'Serrana'},
  {label:'Sertãozinho',value:'Sertãozinho'},
  {label:'Sete Barras',value:'Sete Barras'},
  {label:'Severínia',value:'Severínia'},
  {label:'Silveiras',value:'Silveiras'},
  {label:'Socorro',value:'Socorro'},
  {label:'Sorocaba',value:'Sorocaba'},
  {label:'Sud Mennucci',value:'Sud Mennucci'},
  {label:'Sumaré',value:'Sumaré'},
  {label:'Suzanápolis',value:'Suzanápolis'},
  {label:'Suzano',value:'Suzano'},
  {label:'Tabapuã',value:'Tabapuã'},
  {label:'Tabatinga',value:'Tabatinga'},
  {label:'Taboão da Serra',value:'Taboão da Serra'},
  {label:'Taciba',value:'Taciba'},
  {label:'Taguaí',value:'Taguaí'},
  {label:'Taiaçu',value:'Taiaçu'},
  {label:'Taiúva',value:'Taiúva'},
  {label:'Tambaú',value:'Tambaú'},
  {label:'Tanabi',value:'Tanabi'},
  {label:'Tapiraí',value:'Tapiraí'},
  {label:'Tapiratiba',value:'Tapiratiba'},
  {label:'Taquaral',value:'Taquaral'},
  {label:'Taquaritinga',value:'Taquaritinga'},
  {label:'Taquarituba',value:'Taquarituba'},
  {label:'Taquarivaí',value:'Taquarivaí'},
  {label:'Tarabai',value:'Tarabai'},
  {label:'Tarumã',value:'Tarumã'},
  {label:'Tatuí',value:'Tatuí'},
  {label:'Taubaté',value:'Taubaté'},
  {label:'Tejupá',value:'Tejupá'},
  {label:'Teodoro Sampaio',value:'Teodoro Sampaio'},
  {label:'Terra Roxa',value:'Terra Roxa'},
  {label:'Tietê',value:'Tietê'},
  {label:'Timburi',value:'Timburi'},
  {label:'Torre de Pedra',value:'Torre de Pedra'},
  {label:'Torrinha',value:'Torrinha'},
  {label:'Trabiju',value:'Trabiju'},
  {label:'Tremembé',value:'Tremembé'},
  {label:'Três Fronteiras',value:'Três Fronteiras'},
  {label:'Tuiuti',value:'Tuiuti'},
  {label:'Tupã',value:'Tupã'},
  {label:'Tupi Paulista',value:'Tupi Paulista'},
  {label:'Turiúba',value:'Turiúba'},
  {label:'Turmalina',value:'Turmalina'},
  {label:'Ubarana',value:'Ubarana'},
  {label:'Ubatuba',value:'Ubatuba'},
  {label:'Ubirajara',value:'Ubirajara'},
  {label:'Uchoa',value:'Uchoa'},
  {label:'União Paulista',value:'União Paulista'},
  {label:'Urânia',value:'Urânia'},
  {label:'Uru',value:'Uru'},
  {label:'Urupês',value:'Urupês'},
  {label:'Valentim Gentil',value:'Valentim Gentil'},
  {label:'Valinhos',value:'Valinhos'},
  {label:'Valparaíso',value:'Valparaíso'},
  {label:'Vargem',value:'Vargem'},
  {label:'Vargem Grande do Sul',value:'Vargem Grande do Sul'},
  {label:'Vargem Grande Paulista',value:'Vargem Grande Paulista'},
  {label:'Várzea Paulista',value:'Várzea Paulista'},
  {label:'Vera Cruz',value:'Vera Cruz'},
  {label:'Vinhedo',value:'Vinhedo'},
  {label:'Viradouro',value:'Viradouro'},
  {label:'Vista Alegre do Alto',value:'Vista Alegre do Alto'},
  {label:'Vitória Brasil',value:'Vitória Brasil'},
  {label:'Votorantim',value:'Votorantim'},
  {label:'Votuporanga',value:'Votuporanga'},
  {label:'Zacarias',value:'Zacarias'},

]
export default Cities;
