const Cities  =
[
  {name:'Adolfo',code:'Adolfo'},
  {name:'Aguaí  ',code:'Aguaí  '},
  {name:'Águas da Prata',code:'Águas da Prata'},
  {name:'Águas de Lindóia',code:'Águas de Lindóia'},
  {name:'Águas de Santa Bárbara',code:'Águas de Santa Bárbara'},
  {name:'Águas de São Pedro',code:'Águas de São Pedro'},
  {name:'Agudos',code:'Agudos'},
  {name:'Adolfo',code:'Adolfo'},
  {name:'Alambari',code:'Alambari'},
  {name:'Alfredo Marcondes',code:'Alfredo Marcondes'},
  {name:'Altair',code:'Altair'},
  {name:'Altinópolis',code:'Altinópolis'},
  {name:'Alto Alegre',code:'Alto Alegre'},
  {name:'Alumínio',code:'Alumínio'},
  {name:'Álvares Florence',code:'Álvares Florence'},
  {name:'Álvares Machado',code:'Álvares Machado'},
  {name:'Álvaro de Carvalho',code:'Álvaro de Carvalho'},
  {name:'Alvinlândia',code:'Alvinlândia'},
  {name:'Americana',code:'Americana'},
  {name:'Américo Brasiliense',code:'Américo Brasiliense'},
  {name:'Américo de Campos',code:'Américo de Campos'},
  {name:'Amparo',code:'Amparo'},
  {name:'Analândia',code:'Analândia'},
  {name:'Andradina',code:'Andradina'},
  {name:'Angatuba',code:'Angatuba'},
  {name:'Anhembi',code:'Anhembi'},
  {name:'Anhumas',code:'Anhumas'},
  {name:'Aparecida',code:'Aparecida'},
  {name:'Aparecida d Oeste',code:'Aparecida d Oeste'},
  {name:'Apiaí',code:'Apiaí'},
  {name:'Araçariguama',code:'Araçariguama'},
  {name:'Araçatuba',code:'Araçatuba'},
  {name:'Araçoiaba da Serra',code:'Araçoiaba da Serra'},
  {name:'Aramina',code:'Aramina'},
  {name:'Arandu',code:'Arandu'},
  {name:'Arapeí',code:'Arapeí'},
  {name:'Araraquara',code:'Araraquara'},
  {name:'Araras',code:'Araras'},
  {name:'Arco-Íris',code:'Arco-Íris'},
  {name:'Arealva',code:'Arealva'},
  {name:'Areias',code:'Areias'},
  {name:'Areiópolis',code:'Areiópolis'},
  {name:'Ariranha',code:'Ariranha'},
  {name:'Artur Nogueira',code:'Artur Nogueira'},
  {name:'Arujá',code:'Arujá'},
  {name:'Aspásia',code:'Aspásia'},
  {name:'Assis',code:'Assis'},
  {name:'Atibaia',code:'Atibaia'},
  {name:'Auriflama',code:'Auriflama'},
  {name:'Avaí',code:'Avaí'},
  {name:'Avanhandava',code:'Avanhandava'},
  {name:'Avaré',code:'Avaré'},
  {name:'Bady Bassitt',code:'Bady Bassitt'},
  {name:'Balbinos',code:'Balbinos'},
  {name:'Bálsamo',code:'Bálsamo'},
  {name:'Bananal',code:'Bananal'},
  {name:'Barão de Antonina',code:'Barão de Antonina'},
  {name:'Barbosa',code:'Barbosa'},
  {name:'Bariri',code:'Bariri'},
  {name:'Barra Bonita',code:'Barra Bonita'},
  {name:'Barra do Chapéu',code:'Barra do Chapéu'},
  {name:'Barra do Turvo',code:'Barra do Turvo'},
  {name:'Barretos',code:'Barretos'},
  {name:'Barrinha',code:'Barrinha'},
  {name:'Barueri',code:'Barueri'},
  {name:'Bastos',code:'Bastos'},
  {name:'Batatais',code:'Batatais'},
  {name:'Bauru',code:'Bauru'},
  {name:'Bebedouro',code:'Bebedouro'},
  {name:'Bento de Abreu',code:'Bento de Abreu'},
  {name:'Bernardino de Campos',code:'Bernardino de Campos'},
  {name:'Bertioga',code:'Bertioga'},
  {name:'Bilac',code:'Bilac'},
  {name:'Birigui',code:'Birigui'},
  {name:'Biritiba-Mirim',code:'Biritiba-Mirim'},
  {name:'Boa Esperança do Sul',code:'Boa Esperança do Sul'},
  {name:'Bocaina',code:'Bocaina'},
  {name:'Bofete',code:'Bofete'},
  {name:'Boituva',code:'Boituva'},
  {name:'Bom Jesus dos Perdões',code:'Bom Jesus dos Perdões'},
  {name:'Bom Sucesso de Itararé',code:'Bom Sucesso de Itararé'},
  {name:'Borá',code:'Borá'},
  {name:'Boracéia',code:'Boracéia'},
  {name:'Borborema',code:'Borborema'},
  {name:'Borebi',code:'Borebi'},
  {name:'Botucatu',code:'Botucatu'},
  {name:'Bragança Paulista',code:'Bragança Paulista'},
  {name:'Braúna',code:'Braúna'},
  {name:'Brejo Alegre',code:'Brejo Alegre'},
  {name:'Brodowski',code:'Brodowski'},
  {name:'Brotas',code:'Brotas'},
  {name:'Buri',code:'Buri'},
  {name:'Buritama',code:'Buritama'},
  {name:'Buritizal',code:'Buritizal'},
  {name:'Cabrália Paulista',code:'Cabrália Paulista'},
  {name:'Cabreúva',code:'Cabreúva'},
  {name:'Caçapava',code:'Caçapava'},
  {name:'Cachoeira Paulista',code:'Cachoeira Paulista'},
  {name:'Caconde',code:'Caconde'},
  {name:'Cafelândia',code:'Cafelândia'},
  {name:'Caiabu',code:'Caiabu'},
  {name:'Caieiras',code:'Caieiras'},
  {name:'Caiuá',code:'Caiuá'},
  {name:'Cajamar',code:'Cajamar'},
  {name:'Cajati',code:'Cajati'},
  {name:'Cajobi',code:'Cajobi'},
  {name:'Cajuru',code:'Cajuru'},
  {name:'Campina do Monte Alegre',code:'Campina do Monte Alegre'},
  {name:'Campinas',code:'Campinas'},
  {name:'Campo Limpo Paulista',code:'Campo Limpo Paulista'},
  {name:'Campos do Jordão',code:'Campos do Jordão'},
  {name:'Campos Novos Paulista',code:'Campos Novos Paulista'},
  {name:'Cananéia',code:'Cananéia'},
  {name:'Canas',code:'Canas'},
  {name:'Cândido Mota',code:'Cândido Mota'},
  {name:'Cândido Rodrigues',code:'Cândido Rodrigues'},
  {name:'Canitar',code:'Canitar'},
  {name:'Capão Bonito',code:'Capão Bonito'},
  {name:'Capela do Alto',code:'Capela do Alto'},
  {name:'Capivari',code:'Capivari'},
  {name:'Caraguatatuba',code:'Caraguatatuba'},
  {name:'Carapicuíba',code:'Carapicuíba'},
  {name:'Cardoso',code:'Cardoso'},
  {name:'Casa Branca',code:'Casa Branca'},
  {name:'Cássia dos Coqueiros',code:'Cássia dos Coqueiros'},
  {name:'Castilho',code:'Castilho'},
  {name:'Catanduva',code:'Catanduva'},
  {name:'Catiguá',code:'Catiguá'},
  {name:'Cedral',code:'Cedral'},
  {name:'Cerqueira César',code:'Cerqueira César'},
  {name:'Cerquilho',code:'Cerquilho'},
  {name:'Cesário Lange',code:'Cesário Lange'},
  {name:'Charqueada',code:'Charqueada'},
  {name:'Chavantes',code:'Chavantes'},
  {name:'Clementina',code:'Clementina'},
  {name:'Colina',code:'Colina'},
  {name:'Colômbia',code:'Colômbia'},
  {name:'Conchal',code:'Conchal'},
  {name:'Conchas',code:'Conchas'},
  {name:'Cordeirópolis',code:'Cordeirópolis'},
  {name:'Coroados',code:'Coroados'},
  {name:'Coronel Macedo',code:'Coronel Macedo'},
  {name:'Corumbataí',code:'Corumbataí'},
  {name:'Cosmópolis',code:'Cosmópolis'},
  {name:'Cosmorama',code:'Cosmorama'},
  {name:'Cotia',code:'Cotia'},
  {name:'Cravinhos',code:'Cravinhos'},
  {name:'Cristais Paulista',code:'Cristais Paulista'},
  {name:'Cruzália',code:'Cruzália'},
  {name:'Cruzeiro',code:'Cruzeiro'},
  {name:'Cubatão',code:'Cubatão'},
  {name:'Cunha',code:'Cunha'},
  {name:'Descalvado',code:'Descalvado'},
  {name:'Diadema',code:'Diadema'},
  {name:'Dirce Reis',code:'Dirce Reis'},
  {name:'Divinolândia',code:'Divinolândia'},
  {name:'Dobrada',code:'Dobrada'},
  {name:'Dois Córregos',code:'Dois Córregos'},
  {name:'Dolcinópolis',code:'Dolcinópolis'},
  {name:'Dourado',code:'Dourado'},
  {name:'Dracena',code:'Dracena'},
  {name:'Duartina',code:'Duartina'},
  {name:'Dumont',code:'Dumont'},
  {name:'Echaporã',code:'Echaporã'},
  {name:'Eldorado',code:'Eldorado'},
  {name:'Elias Fausto',code:'Elias Fausto'},
  {name:'Elisiário',code:'Elisiário'},
  {name:'Embaúba',code:'Embaúba'},
  {name:'Embu',code:'Embu'},
  {name:'Embu-Guaçu',code:'Embu-Guaçu'},
  {name:'Emilianópolis',code:'Emilianópolis'},
  {name:'Engenheiro Coelho',code:'Engenheiro Coelho'},
  {name:'Espírito Santo do Pinhal',code:'Espírito Santo do Pinhal'},
  {name:'Espírito Santo do Turvo',code:'Espírito Santo do Turvo'},
  {name:'Estiva Gerbi',code:'Estiva Gerbi'},
  {name:'Estrela do Norte',code:'Estrela do Norte'},
  {name:'Estrela d Oeste',code:'Estrela d Oeste'},
  {name:'Euclides da Cunha Paulista',code:'Euclides da Cunha Paulista'},
  {name:'Fartura',code:'Fartura'},
  {name:'Fernando Prestes',code:'Fernando Prestes'},
  {name:'Fernandópolis',code:'Fernandópolis'},
  {name:'Fernão',code:'Fernão'},
  {name:'Ferraz de Vasconcelos',code:'Ferraz de Vasconcelos'},
  {name:'Flora Rica',code:'Flora Rica'},
  {name:'Floreal',code:'Floreal'},
  {name:'Flórida Paulista',code:'Flórida Paulista'},
  {name:'Florínia',code:'Florínia'},
  {name:'Franca',code:'Franca'},
  {name:'Francisco Morato',code:'Francisco Morato'},
  {name:'Franco da Rocha',code:'Franco da Rocha'},
  {name:'Gabriel Monteiro',code:'Gabriel Monteiro'},
  {name:'Gália',code:'Gália'},
  {name:'Garça',code:'Garça'},
  {name:'Gastão Vidigal',code:'Gastão Vidigal'},
  {name:'Gavião Peixoto',code:'Gavião Peixoto'},
  {name:'General Salgado',code:'General Salgado'},
  {name:'Getulina',code:'Getulina'},
  {name:'Glicério',code:'Glicério'},
  {name:'Guaiçara',code:'Guaiçara'},
  {name:'Guaimbê',code:'Guaimbê'},
  {name:'Guaíra',code:'Guaíra'},
  {name:'Guapiaçu',code:'Guapiaçu'},
  {name:'Guapiara',code:'Guapiara'},
  {name:'Guará',code:'Guará'},
  {name:'Guaraçaí',code:'Guaraçaí'},
  {name:'Guaraci',code:'Guaraci'},
  {name:'Guarani d Oeste',code:'Guarani d Oeste'},
  {name:'Guarantã',code:'Guarantã'},
  {name:'Guararapes',code:'Guararapes'},
  {name:'Guararema',code:'Guararema'},
  {name:'Guaratinguetá',code:'Guaratinguetá'},
  {name:'Guareí',code:'Guareí'},
  {name:'Guariba',code:'Guariba'},
  {name:'Guarujá',code:'Guarujá'},
  {name:'Guarulhos',code:'Guarulhos'},
  {name:'Guatapará',code:'Guatapará'},
  {name:'Guzolândia',code:'Guzolândia'},
  {name:'Herculândia',code:'Herculândia'},
  {name:'Holambra',code:'Holambra'},
  {name:'Hortolândia',code:'Hortolândia'},
  {name:'Iacanga',code:'Iacanga'},
  {name:'Iacri',code:'Iacri'},
  {name:'Iaras',code:'Iaras'},
  {name:'Ibaté',code:'Ibaté'},
  {name:'Ibirá',code:'Ibirá'},
  {name:'Ibirarema',code:'Ibirarema'},
  {name:'Ibitinga',code:'Ibitinga'},
  {name:'Ibiúna',code:'Ibiúna'},
  {name:'Icém',code:'Icém'},
  {name:'Iepê',code:'Iepê'},
  {name:'Igaraçu do Tietê',code:'Igaraçu do Tietê'},
  {name:'Igarapava',code:'Igarapava'},
  {name:'Igaratá',code:'Igaratá'},
  {name:'Iguape',code:'Iguape'},
  {name:'Ilha Comprida',code:'Ilha Comprida'},
  {name:'Ilha Solteira',code:'Ilha Solteira'},
  {name:'Ilhabela',code:'Ilhabela'},
  {name:'Indaiatuba',code:'Indaiatuba'},
  {name:'Indiana',code:'Indiana'},
  {name:'Indiaporã',code:'Indiaporã'},
  {name:'Inúbia Paulista',code:'Inúbia Paulista'},
  {name:'Ipaussu',code:'Ipaussu'},
  {name:'Iperó',code:'Iperó'},
  {name:'Ipeúna',code:'Ipeúna'},
  {name:'Ipiguá',code:'Ipiguá'},
  {name:'Iporanga',code:'Iporanga'},
  {name:'Ipuã',code:'Ipuã'},
  {name:'Iracemápolis',code:'Iracemápolis'},
  {name:'Irapuã',code:'Irapuã'},
  {name:'Irapuru',code:'Irapuru'},
  {name:'Itaberá',code:'Itaberá'},
  {name:'Itaí',code:'Itaí'},
  {name:'Itajobi',code:'Itajobi'},
  {name:'Itaju',code:'Itaju'},
  {name:'Itanhaém',code:'Itanhaém'},
  {name:'Itaóca',code:'Itaóca'},
  {name:'Itapecerica da Serra',code:'Itapecerica da Serra'},
  {name:'Itapetininga',code:'Itapetininga'},
  {name:'Itapeva',code:'Itapeva'},
  {name:'Itapevi',code:'Itapevi'},
  {name:'Itapira',code:'Itapira'},
  {name:'Itapirapuã Paulista',code:'Itapirapuã Paulista'},
  {name:'Itápolis',code:'Itápolis'},
  {name:'Itaporanga',code:'Itaporanga'},
  {name:'Itapuí',code:'Itapuí'},
  {name:'Itapura',code:'Itapura'},
  {name:'Itaquaquecetuba',code:'Itaquaquecetuba'},
  {name:'Itararé',code:'Itararé'},
  {name:'Itariri',code:'Itariri'},
  {name:'Itatiba',code:'Itatiba'},
  {name:'Itatinga',code:'Itatinga'},
  {name:'Itirapina',code:'Itirapina'},
  {name:'Itirapuã',code:'Itirapuã'},
  {name:'Itobi',code:'Itobi'},
  {name:'Itu',code:'Itu'},
  {name:'Itupeva',code:'Itupeva'},
  {name:'Ituverava',code:'Ituverava'},
  {name:'Jaborandi',code:'Jaborandi'},
  {name:'Jaboticabal',code:'Jaboticabal'},
  {name:'Jacareí',code:'Jacareí'},
  {name:'Jaci',code:'Jaci'},
  {name:'Jacupiranga',code:'Jacupiranga'},
  {name:'Jaguariúna',code:'Jaguariúna'},
  {name:'Jales',code:'Jales'},
  {name:'Jambeiro',code:'Jambeiro'},
  {name:'Jandira',code:'Jandira'},
  {name:'Jardinópolis',code:'Jardinópolis'},
  {name:'Jarinu',code:'Jarinu'},
  {name:'Jaú',code:'Jaú'},
  {name:'Jeriquara',code:'Jeriquara'},
  {name:'Joanópolis',code:'Joanópolis'},
  {name:'João Ramalho',code:'João Ramalho'},
  {name:'José Bonifácio',code:'José Bonifácio'},
  {name:'Júlio Mesquita',code:'Júlio Mesquita'},
  {name:'Jumirim',code:'Jumirim'},
  {name:'Jundiaí',code:'Jundiaí'},
  {name:'Junqueirópolis',code:'Junqueirópolis'},
  {name:'Juquiá',code:'Juquiá'},
  {name:'Juquitiba',code:'Juquitiba'},
  {name:'Lagoinha',code:'Lagoinha'},
  {name:'Laranjal Paulista',code:'Laranjal Paulista'},
  {name:'Lavínia',code:'Lavínia'},
  {name:'Lavrinhas',code:'Lavrinhas'},
  {name:'Leme',code:'Leme'},
  {name:'Lençóis Paulista',code:'Lençóis Paulista'},
  {name:'Limeira',code:'Limeira'},
  {name:'Lindóia',code:'Lindóia'},
  {name:'Lins',code:'Lins'},
  {name:'Lorena',code:'Lorena'},
  {name:'Lourdes',code:'Lourdes'},
  {name:'Louveira',code:'Louveira'},
  {name:'Lucélia',code:'Lucélia'},
  {name:'Lucianópolis',code:'Lucianópolis'},
  {name:'Luís Antônio',code:'Luís Antônio'},
  {name:'Luiziânia',code:'Luiziânia'},
  {name:'Lupércio',code:'Lupércio'},
  {name:'Lutécia',code:'Lutécia'},
  {name:'Macatuba',code:'Macatuba'},
  {name:'Macaubal',code:'Macaubal'},
  {name:'Macedônia',code:'Macedônia'},
  {name:'Magda',code:'Magda'},
  {name:'Mairinque',code:'Mairinque'},
  {name:'Mairiporã',code:'Mairiporã'},
  {name:'Manduri',code:'Manduri'},
  {name:'Marabá Paulista',code:'Marabá Paulista'},
  {name:'Maracaí',code:'Maracaí'},
  {name:'Marapoama',code:'Marapoama'},
  {name:'Mariápolis',code:'Mariápolis'},
  {name:'Marília',code:'Marília'},
  {name:'Marinópolis',code:'Marinópolis'},
  {name:'Martinópolis',code:'Martinópolis'},
  {name:'Matão',code:'Matão'},
  {name:'Mauá',code:'Mauá'},
  {name:'Mendonça',code:'Mendonça'},
  {name:'Meridiano',code:'Meridiano'},
  {name:'Mesópolis',code:'Mesópolis'},
  {name:'Miguelópolis',code:'Miguelópolis'},
  {name:'Mineiros do Tietê',code:'Mineiros do Tietê'},
  {name:'Mira Estrela',code:'Mira Estrela'},
  {name:'Miracatu',code:'Miracatu'},
  {name:'Mirandópolis',code:'Mirandópolis'},
  {name:'Mirante do Paranapanema',code:'Mirante do Paranapanema'},
  {name:'Mirassol',code:'Mirassol'},
  {name:'Mirassolândia',code:'Mirassolândia'},
  {name:'Mococa',code:'Mococa'},
  {name:'Mogi das Cruzes',code:'Mogi das Cruzes'},
  {name:'Mogi Guaçu',code:'Mogi Guaçu'},
  {name:'Moji Mirim',code:'Moji Mirim'},
  {name:'Mombuca',code:'Mombuca'},
  {name:'Monções',code:'Monções'},
  {name:'Mongaguá',code:'Mongaguá'},
  {name:'Monte Alegre do Sul',code:'Monte Alegre do Sul'},
  {name:'Monte Alto',code:'Monte Alto'},
  {name:'Monte Aprazível',code:'Monte Aprazível'},
  {name:'Monte Azul Paulista',code:'Monte Azul Paulista'},
  {name:'Monte Castelo',code:'Monte Castelo'},
  {name:'Monte Mor',code:'Monte Mor'},
  {name:'Monteiro Lobato',code:'Monteiro Lobato'},
  {name:'Morro Agudo',code:'Morro Agudo'},
  {name:'Morungaba',code:'Morungaba'},
  {name:'Motuca',code:'Motuca'},
  {name:'Murutinga do Sul',code:'Murutinga do Sul'},
  {name:'Nantes',code:'Nantes'},
  {name:'Narandiba',code:'Narandiba'},
  {name:'Natividade da Serra',code:'Natividade da Serra'},
  {name:'Nazaré Paulista',code:'Nazaré Paulista'},
  {name:'Neves Paulista',code:'Neves Paulista'},
  {name:'Nhandeara',code:'Nhandeara'},
  {name:'Nipoã',code:'Nipoã'},
  {name:'Nova Aliança',code:'Nova Aliança'},
  {name:'Nova Campina',code:'Nova Campina'},
  {name:'Nova Canaã Paulista',code:'Nova Canaã Paulista'},
  {name:'Nova Castilho',code:'Nova Castilho'},
  {name:'Nova Europa',code:'Nova Europa'},
  {name:'Nova Granada',code:'Nova Granada'},
  {name:'Nova Guataporanga',code:'Nova Guataporanga'},
  {name:'Nova Independência',code:'Nova Independência'},
  {name:'Nova Luzitânia',code:'Nova Luzitânia'},
  {name:'Nova Odessa',code:'Nova Odessa'},
  {name:'Novais',code:'Novais'},
  {name:'Novo Horizonte',code:'Novo Horizonte'},
  {name:'Nuporanga',code:'Nuporanga'},
  {name:'Ocauçu',code:'Ocauçu'},
  {name:'Óleo',code:'Óleo'},
  {name:'Olímpia',code:'Olímpia'},
  {name:'Onda Verde',code:'Onda Verde'},
  {name:'Oriente',code:'Oriente'},
  {name:'Orindiúva',code:'Orindiúva'},
  {name:'Orlândia',code:'Orlândia'},
  {name:'Osasco',code:'Osasco'},
  {name:'Oscar Bressane',code:'Oscar Bressane'},
  {name:'Osvaldo Cruz',code:'Osvaldo Cruz'},
  {name:'Ourinhos',code:'Ourinhos'},
  {name:'Ouro Verde',code:'Ouro Verde'},
  {name:'Ouroeste',code:'Ouroeste'},
  {name:'Pacaembu',code:'Pacaembu'},
  {name:'Palestina',code:'Palestina'},
  {name:'Palmares Paulista',code:'Palmares Paulista'},
  {name:'Palmeira d Oeste',code:'Palmeira d Oeste'},
  {name:'Palmital',code:'Palmital'},
  {name:'Panorama',code:'Panorama'},
  {name:'Paraguaçu Paulista',code:'Paraguaçu Paulista'},
  {name:'Paraibuna',code:'Paraibuna'},
  {name:'Paraíso',code:'Paraíso'},
  {name:'Paranapanema',code:'Paranapanema'},
  {name:'Paranapuã',code:'Paranapuã'},
  {name:'Parapuã',code:'Parapuã'},
  {name:'Pardinho',code:'Pardinho'},
  {name:'Pariquera-Açu',code:'Pariquera-Açu'},
  {name:'Parisi',code:'Parisi'},
  {name:'Patrocínio Paulista',code:'Patrocínio Paulista'},
  {name:'Paulicéia',code:'Paulicéia'},
  {name:'Paulínia',code:'Paulínia'},
  {name:'Paulistânia',code:'Paulistânia'},
  {name:'Paulo de Faria',code:'Paulo de Faria'},
  {name:'Pederneiras',code:'Pederneiras'},
  {name:'Pedra Bela',code:'Pedra Bela'},
  {name:'Pedranópolis',code:'Pedranópolis'},
  {name:'Pedregulho',code:'Pedregulho'},
  {name:'Pedreira',code:'Pedreira'},
  {name:'Pedrinhas Paulista',code:'Pedrinhas Paulista'},
  {name:'Pedro de Toledo',code:'Pedro de Toledo'},
  {name:'Penápolis',code:'Penápolis'},
  {name:'Pereira Barreto',code:'Pereira Barreto'},
  {name:'Pereiras',code:'Pereiras'},
  {name:'Peruíbe',code:'Peruíbe'},
  {name:'Piacatu',code:'Piacatu'},
  {name:'Piedade',code:'Piedade'},
  {name:'Pilar do Sul',code:'Pilar do Sul'},
  {name:'Pindamonhangaba',code:'Pindamonhangaba'},
  {name:'Pindorama',code:'Pindorama'},
  {name:'Pinhalzinho',code:'Pinhalzinho'},
  {name:'Piquerobi',code:'Piquerobi'},
  {name:'Piquete',code:'Piquete'},
  {name:'Piracaia',code:'Piracaia'},
  {name:'Piracicaba',code:'Piracicaba'},
  {name:'Piraju',code:'Piraju'},
  {name:'Pirajuí',code:'Pirajuí'},
  {name:'Pirangi',code:'Pirangi'},
  {name:'Pirapora do Bom Jesus',code:'Pirapora do Bom Jesus'},
  {name:'Pirapozinho',code:'Pirapozinho'},
  {name:'Pirassununga',code:'Pirassununga'},
  {name:'Piratininga',code:'Piratininga'},
  {name:'Pitangueiras',code:'Pitangueiras'},
  {name:'Planalto',code:'Planalto'},
  {name:'Platina',code:'Platina'},
  {name:'Poá',code:'Poá'},
  {name:'Poloni',code:'Poloni'},
  {name:'Pompéia',code:'Pompéia'},
  {name:'Pongaí',code:'Pongaí'},
  {name:'Pontal',code:'Pontal'},
  {name:'Pontalinda',code:'Pontalinda'},
  {name:'Pontes Gestal',code:'Pontes Gestal'},
  {name:'Populina',code:'Populina'},
  {name:'Porangaba',code:'Porangaba'},
  {name:'Porto Feliz',code:'Porto Feliz'},
  {name:'Porto Ferreira',code:'Porto Ferreira'},
  {name:'Potim',code:'Potim'},
  {name:'Potirendaba',code:'Potirendaba'},
  {name:'Pracinha',code:'Pracinha'},
  {name:'Pradópolis',code:'Pradópolis'},
  {name:'Praia Grande',code:'Praia Grande'},
  {name:'Pratânia',code:'Pratânia'},
  {name:'Presidente Alves',code:'Presidente Alves'},
  {name:'Presidente Bernardes',code:'Presidente Bernardes'},
  {name:'Presidente Epitácio',code:'Presidente Epitácio'},
  {name:'Presidente Prudente',code:'Presidente Prudente'},
  {name:'Presidente Venceslau',code:'Presidente Venceslau'},
  {name:'Promissão',code:'Promissão'},
  {name:'Quadra',code:'Quadra'},
  {name:'Quatá',code:'Quatá'},
  {name:'Queiroz',code:'Queiroz'},
  {name:'Queluz',code:'Queluz'},
  {name:'Quintana',code:'Quintana'},
  {name:'Rafard',code:'Rafard'},
  {name:'Rancharia',code:'Rancharia'},
  {name:'Redenção da Serra',code:'Redenção da Serra'},
  {name:'Regente Feijó',code:'Regente Feijó'},
  {name:'Reginópolis',code:'Reginópolis'},
  {name:'Registro',code:'Registro'},
  {name:'Restinga',code:'Restinga'},
  {name:'Ribeira',code:'Ribeira'},
  {name:'Ribeirão Bonito',code:'Ribeirão Bonito'},
  {name:'Ribeirão Branco',code:'Ribeirão Branco'},
  {name:'Ribeirão Corrente',code:'Ribeirão Corrente'},
  {name:'Ribeirão do Sul',code:'Ribeirão do Sul'},
  {name:'Ribeirão dos Índios',code:'Ribeirão dos Índios'},
  {name:'Ribeirão Grande',code:'Ribeirão Grande'},
  {name:'Ribeirão Pires',code:'Ribeirão Pires'},
  {name:'Ribeirão Preto',code:'Ribeirão Preto'},
  {name:'Rifaina',code:'Rifaina'},
  {name:'Rincão',code:'Rincão'},
  {name:'Rinópolis',code:'Rinópolis'},
  {name:'Rio Claro',code:'Rio Claro'},
  {name:'Rio das Pedras',code:'Rio das Pedras'},
  {name:'Rio Grande da Serra',code:'Rio Grande da Serra'},
  {name:'Riolândia',code:'Riolândia'},
  {name:'Riversul',code:'Riversul'},
  {name:'Rosana',code:'Rosana'},
  {name:'Roseira',code:'Roseira'},
  {name:'Rubiácea',code:'Rubiácea'},
  {name:'Rubinéia',code:'Rubinéia'},
  {name:'Sabino',code:'Sabino'},
  {name:'Sagres',code:'Sagres'},
  {name:'Sales',code:'Sales'},
  {name:'Sales Oliveira',code:'Sales Oliveira'},
  {name:'Salesópolis',code:'Salesópolis'},
  {name:'Salmourão',code:'Salmourão'},
  {name:'Saltinho',code:'Saltinho'},
  {name:'Salto',code:'Salto'},
  {name:'Salto de Pirapora',code:'Salto de Pirapora'},
  {name:'Salto Grande',code:'Salto Grande'},
  {name:'Sandovalina',code:'Sandovalina'},
  {name:'Santa Adélia',code:'Santa Adélia'},
  {name:'Santa Albertina',code:'Santa Albertina'},
  {name:'Santa Bárbara d Oeste',code:'Santa Bárbara d Oeste'},
  {name:'Santa Branca',code:'Santa Branca'},
  {name:'Santa Clara d Oeste',code:'Santa Clara d Oeste'},
  {name:'Santa Cruz da Conceição',code:'Santa Cruz da Conceição'},
  {name:'Santa Cruz da Esperança',code:'Santa Cruz da Esperança'},
  {name:'Santa Cruz das Palmeiras',code:'Santa Cruz das Palmeiras'},
  {name:'Santa Cruz do Rio Pardo',code:'Santa Cruz do Rio Pardo'},
  {name:'Santa Ernestina',code:'Santa Ernestina'},
  {name:'Santa Fé do Sul',code:'Santa Fé do Sul'},
  {name:'Santa Gertrudes',code:'Santa Gertrudes'},
  {name:'Santa Isabel',code:'Santa Isabel'},
  {name:'Santa Lúcia',code:'Santa Lúcia'},
  {name:'Santa Maria da Serra',code:'Santa Maria da Serra'},
  {name:'Santa Mercedes',code:'Santa Mercedes'},
  {name:'Santa Rita do Passa Quatro',code:'Santa Rita do Passa Quatro'},
  {name:'Santa Rita d Oeste',code:'Santa Rita d Oeste'},
  {name:'Santa Rosa de Viterbo',code:'Santa Rosa de Viterbo'},
  {name:'Santa Salete',code:'Santa Salete'},
  {name:'Santana da Ponte Pensa',code:'Santana da Ponte Pensa'},
  {name:'Santana de Parnaíba',code:'Santana de Parnaíba'},
  {name:'Santo Anastácio',code:'Santo Anastácio'},
  {name:'Santo André',code:'Santo André'},
  {name:'Santo Antônio da Alegria',code:'Santo Antônio da Alegria'},
  {name:'Santo Antônio de Posse',code:'Santo Antônio de Posse'},
  {name:'Santo Antônio do Aracanguá',code:'Santo Antônio do Aracanguá'},
  {name:'Santo Antônio do Jardim',code:'Santo Antônio do Jardim'},
  {name:'Santo Antônio do Pinhal',code:'Santo Antônio do Pinhal'},
  {name:'Santo Expedito',code:'Santo Expedito'},
  {name:'Santópolis do Aguapeí',code:'Santópolis do Aguapeí'},
  {name:'Santos',code:'Santos'},
  {name:'São Bento do Sapucaí',code:'São Bento do Sapucaí'},
  {name:'São Bernardo do Campo',code:'São Bernardo do Campo'},
  {name:'São Caetano do Sul',code:'São Caetano do Sul'},
  {name:'São Carlos',code:'São Carlos'},
  {name:'São Francisco',code:'São Francisco'},
  {name:'São João da Boa Vista',code:'São João da Boa Vista'},
  {name:'São João das Duas Pontes',code:'São João das Duas Pontes'},
  {name:'São João de Iracema',code:'São João de Iracema'},
  {name:'São João do Pau d Alho',code:'São João do Pau d Alho'},
  {name:'São Joaquim da Barra',code:'São Joaquim da Barra'},
  {name:'São José da Bela Vista',code:'São José da Bela Vista'},
  {name:'São José do Barreiro',code:'São José do Barreiro'},
  {name:'São José do Rio Pardo',code:'São José do Rio Pardo'},
  {name:'São José do Rio Preto',code:'São José do Rio Preto'},
  {name:'São José dos Campos',code:'São José dos Campos'},
  {name:'São Lourenço da Serra',code:'São Lourenço da Serra'},
  {name:'São Luís do Paraitinga',code:'São Luís do Paraitinga'},
  {name:'São Manuel',code:'São Manuel'},
  {name:'São Miguel Arcanjo',code:'São Miguel Arcanjo'},
  {name:'São Paulo',code:'São Paulo'},
  {name:'São Pedro',code:'São Pedro'},
  {name:'São Pedro do Turvo',code:'São Pedro do Turvo'},
  {name:'São Roque',code:'São Roque'},
  {name:'São Sebastião',code:'São Sebastião'},
  {name:'São Sebastião da Grama',code:'São Sebastião da Grama'},
  {name:'São Simão',code:'São Simão'},
  {name:'São Vicente',code:'São Vicente'},
  {name:'Sarapuí',code:'Sarapuí'},
  {name:'Sarutaiá',code:'Sarutaiá'},
  {name:'Sebastianópolis do Sul',code:'Sebastianópolis do Sul'},
  {name:'Serra Azul',code:'Serra Azul'},
  {name:'Serra Negra',code:'Serra Negra'},
  {name:'Serrana',code:'Serrana'},
  {name:'Sertãozinho',code:'Sertãozinho'},
  {name:'Sete Barras',code:'Sete Barras'},
  {name:'Severínia',code:'Severínia'},
  {name:'Silveiras',code:'Silveiras'},
  {name:'Socorro',code:'Socorro'},
  {name:'Sorocaba',code:'Sorocaba'},
  {name:'Sud Mennucci',code:'Sud Mennucci'},
  {name:'Sumaré',code:'Sumaré'},
  {name:'Suzanápolis',code:'Suzanápolis'},
  {name:'Suzano',code:'Suzano'},
  {name:'Tabapuã',code:'Tabapuã'},
  {name:'Tabatinga',code:'Tabatinga'},
  {name:'Taboão da Serra',code:'Taboão da Serra'},
  {name:'Taciba',code:'Taciba'},
  {name:'Taguaí',code:'Taguaí'},
  {name:'Taiaçu',code:'Taiaçu'},
  {name:'Taiúva',code:'Taiúva'},
  {name:'Tambaú',code:'Tambaú'},
  {name:'Tanabi',code:'Tanabi'},
  {name:'Tapiraí',code:'Tapiraí'},
  {name:'Tapiratiba',code:'Tapiratiba'},
  {name:'Taquaral',code:'Taquaral'},
  {name:'Taquaritinga',code:'Taquaritinga'},
  {name:'Taquarituba',code:'Taquarituba'},
  {name:'Taquarivaí',code:'Taquarivaí'},
  {name:'Tarabai',code:'Tarabai'},
  {name:'Tarumã',code:'Tarumã'},
  {name:'Tatuí',code:'Tatuí'},
  {name:'Taubaté',code:'Taubaté'},
  {name:'Tejupá',code:'Tejupá'},
  {name:'Teodoro Sampaio',code:'Teodoro Sampaio'},
  {name:'Terra Roxa',code:'Terra Roxa'},
  {name:'Tietê',code:'Tietê'},
  {name:'Timburi',code:'Timburi'},
  {name:'Torre de Pedra',code:'Torre de Pedra'},
  {name:'Torrinha',code:'Torrinha'},
  {name:'Trabiju',code:'Trabiju'},
  {name:'Tremembé',code:'Tremembé'},
  {name:'Três Fronteiras',code:'Três Fronteiras'},
  {name:'Tuiuti',code:'Tuiuti'},
  {name:'Tupã',code:'Tupã'},
  {name:'Tupi Paulista',code:'Tupi Paulista'},
  {name:'Turiúba',code:'Turiúba'},
  {name:'Turmalina',code:'Turmalina'},
  {name:'Ubarana',code:'Ubarana'},
  {name:'Ubatuba',code:'Ubatuba'},
  {name:'Ubirajara',code:'Ubirajara'},
  {name:'Uchoa',code:'Uchoa'},
  {name:'União Paulista',code:'União Paulista'},
  {name:'Urânia',code:'Urânia'},
  {name:'Uru',code:'Uru'},
  {name:'Urupês',code:'Urupês'},
  {name:'Valentim Gentil',code:'Valentim Gentil'},
  {name:'Valinhos',code:'Valinhos'},
  {name:'Valparaíso',code:'Valparaíso'},
  {name:'Vargem',code:'Vargem'},
  {name:'Vargem Grande do Sul',code:'Vargem Grande do Sul'},
  {name:'Vargem Grande Paulista',code:'Vargem Grande Paulista'},
  {name:'Várzea Paulista',code:'Várzea Paulista'},
  {name:'Vera Cruz',code:'Vera Cruz'},
  {name:'Vinhedo',code:'Vinhedo'},
  {name:'Viradouro',code:'Viradouro'},
  {name:'Vista Alegre do Alto',code:'Vista Alegre do Alto'},
  {name:'Vitória Brasil',code:'Vitória Brasil'},
  {name:'Votorantim',code:'Votorantim'},
  {name:'Votuporanga',code:'Votuporanga'},
  {name:'Zacarias',code:'Zacarias'},

]
export default Cities;
